# Generated by Django 5.1 on 2024-10-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgame', '0002_alter_tournament_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
