# Generated by Django 5.1 on 2024-10-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgame', '0003_match_is_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
