# Generated by Django 5.1 on 2024-09-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_uid',
            field=models.CharField(default='yRK2bJmdmC', editable=False, max_length=10),
        ),
    ]
