# Generated by Django 5.1 on 2024-09-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_customuser_custom_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='custom_uid',
            field=models.CharField(default='JqnIarWP27Jbc8V5AwYDcHPqiEHOqEFs', editable=False, max_length=32),
        ),
    ]
