# Generated by Django 5.1 on 2024-09-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_customuser_custom_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='custom_uid',
            field=models.CharField(default='4h1es0hSmw5Xyu3CgoNCJ8tsoLGUwoSD', editable=False, max_length=32, unique=True),
        ),
    ]
