# Generated by Django 5.1 on 2024-09-08 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_customuser_custom_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pendingRequests',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='friends',
        ),
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
