# Generated by Django 5.1 on 2024-09-09 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_customuser_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='blocked',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
