# Generated by Django 5.1 on 2024-09-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_alter_customuser_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
