# Generated by Django 5.1 on 2024-09-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_customuser_verified_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='game_theme',
            field=models.ImageField(blank=True, null=True, upload_to='themes'),
        ),
    ]
